import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Agent skill bundles vendored in by `prisma skills sync`.
    ".agents/**",
    ".claude/**",
    ".cursor/**",
    ".devin/**",
    // Generated by Payload and the Prisma contract emitter.
    "payload-types.ts",
    "src/prisma/contract.d.ts",
    "migrations/**",
  ]),
]);

export default eslintConfig;
